### ISSUE TITLE
Section images on home page not showing

### ISSUE THREAD

**Issue by Suds-p** [meowkash/meowkash.github.io#2]
Images behind each section on the home page do not load.
Tested on the following browsers:
- Brave
- Safari
- Firefox

<img width="1414" alt="Screenshot 2024-09-15 at 12 13 36 PM" src="https://github.com/user-attachments/assets/0d3ab964-f8f7-4386-84f5-b063941a763b">

**Comment by meowkash** [comment]
Setting custom style for ```<article>``` in ```tiles.html``` along with removing ```baseurl``` did the trick
